export const categories = [
  { id: 'all', label: '전체' }, { id: 'space', label: '공간·숙박' },
  { id: 'commerce', label: '쇼핑·브랜드' }, { id: 'business', label: '기업·서비스' },
  { id: 'industry', label: '산업·연구' }, { id: 'education', label: '교육' }, { id: 'gaming', label: '게이밍' },
];
export const templates = [
  { id: 'onyu', title: 'ONYU', type: '모델하우스', category: 'space', image: '/thumbnails/onyu.jpg', url: 'https://atelier-house-seven.vercel.app/', description: '중정을 중심으로 이어지는 주택을 소개합니다. 스크롤에 맞춰 외부에서 실내로 이동하며 공간과 평면을 함께 살펴볼 수 있습니다.', features: ['스크롤로 둘러보는 공간', '평면도와 공간 소개', '방문 예약 화면'], keywords: 'architecture residence 건축 주택 온유' },
  { id: 'serein', title: 'SEREIN', type: '호텔·스테이', category: 'space', image: '/thumbnails/serein.jpg', url: 'https://serein-retreat.vercel.app/', description: '해안가 스테이의 객실과 머무는 경험을 소개합니다. 바다 풍경에서 시작해 객실 비교와 예약 화면으로 이어집니다.', features: ['스크롤에 반응하는 풍경', '객실 비교', '예약 데모'], keywords: 'hospitality hotel retreat 숙박 여행 세레인' },
  { id: 'interior', title: 'Minimal Interior', type: '가구·인테리어', category: 'space', image: '/thumbnails/interior.jpg', url: 'https://HMSOFT-WEB.github.io/interior_template11/', description: '가구와 공간 사진을 중심으로 구성한 인테리어 카탈로그입니다. 제품의 소재와 형태를 큰 이미지로 보여줍니다.', features: ['공간 중심의 제품 소개', '가구 컬렉션', '제품 상세 화면'], keywords: 'furniture interior 미니멀 공간' },
  { id: 'cosmetics', title: 'Vegan Cosmetics', type: '스킨케어', category: 'commerce', image: '/thumbnails/cosmetics.jpg', url: 'https://HMSOFT-WEB.github.io/cosmetics_template7/', description: '스킨케어 제품과 브랜드의 원료 이야기를 연결합니다. 제품 이미지와 사용 목적을 함께 보여주는 뷰티 브랜드 사이트입니다.', features: ['제품 중심의 첫 화면', '원료와 브랜드 소개', '쇼핑 화면'], keywords: 'beauty cosmetics 화장품 비건' },
  { id: 'coffee', title: 'Specialty Coffee', type: '커피·로스터리', category: 'commerce', image: '/thumbnails/coffee.jpg', url: 'https://HMSOFT-WEB.github.io/coffee_template8/', description: '원두와 로스팅 이야기를 담은 커피 브랜드 사이트입니다. 짙은 색감과 커피 사진으로 매장의 분위기를 전달합니다.', features: ['로스터리 소개', '원두 컬렉션', '상품 탐색'], keywords: 'food cafe roastery 카페 커피' },
  { id: 'streetwear', title: 'Streetwear Fashion', type: '패션·컬렉션', category: 'commerce', image: '/thumbnails/streetwear.jpg', url: 'https://HMSOFT-WEB.github.io/streetwear_template10/', description: '컬렉션 출시를 알리는 패션 브랜드 사이트입니다. 캠페인 이미지와 강한 타이포그래피를 중심으로 신상품을 보여줍니다.', features: ['캠페인 비주얼', '신상품 컬렉션', '제품 탐색'], keywords: 'fashion drop 의류 스트리트 패션' },
  { id: 'corporate', title: 'Enterprise Corporate', type: '기업 소개', category: 'business', image: '/thumbnails/corporate.jpg', url: 'https://HMSOFT-WEB.github.io/corporate_template/', description: 'IT와 인프라 기업의 사업 영역을 소개합니다. 서비스, 사업 성과, 기업 정보를 순서대로 살펴볼 수 있는 구성입니다.', features: ['사업 영역 소개', '기업 정보', '문의 동선'], keywords: 'corporate enterprise b2b 회사 기업' },
  { id: 'bio', title: 'Bio Healthcare', type: '바이오·헬스케어', category: 'industry', image: '/thumbnails/bio.jpg', url: 'https://HMSOFT-WEB.github.io/bio_template2/', description: '연구 분야와 기술을 소개하는 바이오 기업 사이트입니다. 분자 구조 비주얼과 밝은 화면으로 연구 내용을 전달합니다.', features: ['연구 분야 소개', '입체 비주얼', '기술 콘텐츠'], keywords: 'science health medical 의료 과학 연구' },
  { id: 'construction', title: 'Heavy Construction', type: '건설·엔지니어링', category: 'industry', image: '/thumbnails/construction.jpg', url: 'https://HMSOFT-WEB.github.io/construction_template3/', description: '건설과 엔지니어링 사업을 소개합니다. 프로젝트, 시공 분야, 기업 역량을 분명하게 구분한 기업 사이트입니다.', features: ['시공 분야 소개', '프로젝트 목록', '회사 정보'], keywords: 'engineering construction 건설 시공' },
  { id: 'commerce', title: 'Global E-Commerce', type: '온라인 스토어', category: 'commerce', image: '/thumbnails/commerce.jpg', url: 'https://HMSOFT-WEB.github.io/ecommerce_template4/', description: '제품 컬렉션과 캠페인을 보여주는 온라인 스토어입니다. 큰 제품 비주얼에서 상품 탐색으로 이어집니다.', features: ['제품 비주얼', '컬렉션 탐색', '쇼핑 화면'], keywords: 'retail product ecommerce 쇼핑몰 이커머스' },
  { id: 'platform', title: 'SaaS Platform', type: '소프트웨어 서비스', category: 'business', image: '/thumbnails/platform.jpg', url: 'https://HMSOFT-WEB.github.io/platform_template5/', description: '클라우드 소프트웨어의 기능과 사용 흐름을 소개합니다. 제품의 주요 기능에서 서비스 도입 안내로 이어집니다.', features: ['서비스 기능 소개', '제품 화면', '도입 안내'], keywords: 'tech software cloud 데이터 플랫폼' },
  { id: 'education', title: 'EdTech Education', type: '교육·온라인 강의', category: 'education', image: '/thumbnails/education.jpg', url: 'https://HMSOFT-WEB.github.io/education_template6/', description: '강좌와 학습 경험을 소개하는 교육 사이트입니다. 교육 프로그램을 탐색하고 강의 정보를 살펴볼 수 있습니다.', features: ['강좌 탐색', '교육 프로그램', '학습 서비스 소개'], keywords: 'learning academy course 에듀테크 학원' },
  { id: 'gaming', title: 'Esports Gear', type: '게이밍 기어', category: 'gaming', image: '/thumbnails/gaming.jpg', url: 'https://HMSOFT-WEB.github.io/gaming_template9/', description: '게이밍 하드웨어를 소개하는 제품 사이트입니다. 어두운 배경 위에 제품 이미지와 주요 사양을 강조합니다.', features: ['하드웨어 비주얼', '제품 사양', '제품 컬렉션'], keywords: 'tech gaming hardware 이스포츠 게임 키보드' },
];
